version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-container
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d
            - ./.docker/nginx/ssl:/etc/nginx/conf.d/ssl
        depends_on:
            -  app

        networks:
            - common-net
    app:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        container_name: laravel_container
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./.docker/php/php-fpm.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/.ssh:/root/.ssh
        tty: true
        ports:
            - "8110:8110"
            - "8112:8112"

        networks:
            common-net:
                aliases:
                    - docker-app


    npm:
        image: node:14
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes:
            - ./:/var/www/html

networks:
    common-net:
        external: true

volumes:
    app:
    npm:


